<?php
/**
 * RealTransactionDetailReport
 *
 * PHP version 5
 *
 * @category Class
 * @package  pitneybowesShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace pitneybowesShipping\shippingApi.model;

use \ArrayAccess;
use \pitneybowesShipping\ObjectSerializer;

/**
 * RealTransactionDetailReport Class Doc Comment
 *
 * @category Class
 * @package  pitneybowesShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RealTransactionDetailReport implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RealTransactionDetailReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'adjustment_reason' => 'string',
        'credit_card_fee' => 'double',
        'custom_message1' => 'string',
        'custom_message2' => 'string',
        'description' => 'string',
        'destination_address' => 'string',
        'destination_country' => 'string',
        'destination_zip' => 'string',
        'developer_id' => 'string',
        'developer_name' => 'string',
        'developer_postage_payment_account_balance' => 'double',
        'developer_postage_payment_method' => 'string',
        'developer_rate_amount' => 'double',
        'developer_rate_plan' => 'string',
        'dimensional_weight_oz' => 'double',
        'external_id' => 'string',
        'international_country_price_group' => 'string',
        'label_fee' => 'string',
        'mail_class' => 'string',
        'merchant_id' => 'string',
        'merchant_name' => 'string',
        'merchant_postage_account_payment_method' => 'string',
        'merchant_rate' => 'double',
        'merchant_rate_plan' => 'string',
        'meter_number' => 'string',
        'origin_zip' => 'string',
        'origination_address' => 'string',
        'package_height_in_inches' => 'double',
        'package_length_in_inches' => 'double',
        'package_type' => 'string',
        'package_type_indicator' => 'string',
        'package_width_in_inches' => 'double',
        'parcel_tracking_number' => 'string',
        'postage_deposit_amount' => 'double',
        'print_status' => 'string',
        'references' => '\pitneybowesShipping\shippingApi.model\Parameter[]',
        'refund_denial_reason' => 'string',
        'refund_requestor' => 'string',
        'refund_status' => 'string',
        'shipment_id' => 'string',
        'shipper_postage_payment_account_balance' => 'double',
        'special_services' => '\pitneybowesShipping\shippingApi.model\SpecialService[]',
        'status' => 'string',
        'transaction_date_time' => '\DateTime',
        'transaction_id' => 'string',
        'transaction_type' => 'string',
        'value_of_goods' => 'double',
        'weight_in_ounces' => 'int',
        'zone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'adjustment_reason' => null,
        'credit_card_fee' => 'double',
        'custom_message1' => null,
        'custom_message2' => null,
        'description' => null,
        'destination_address' => null,
        'destination_country' => null,
        'destination_zip' => null,
        'developer_id' => null,
        'developer_name' => null,
        'developer_postage_payment_account_balance' => 'double',
        'developer_postage_payment_method' => null,
        'developer_rate_amount' => 'double',
        'developer_rate_plan' => null,
        'dimensional_weight_oz' => 'double',
        'external_id' => null,
        'international_country_price_group' => null,
        'label_fee' => null,
        'mail_class' => null,
        'merchant_id' => null,
        'merchant_name' => null,
        'merchant_postage_account_payment_method' => null,
        'merchant_rate' => 'double',
        'merchant_rate_plan' => null,
        'meter_number' => null,
        'origin_zip' => null,
        'origination_address' => null,
        'package_height_in_inches' => 'double',
        'package_length_in_inches' => 'double',
        'package_type' => null,
        'package_type_indicator' => null,
        'package_width_in_inches' => 'double',
        'parcel_tracking_number' => null,
        'postage_deposit_amount' => 'double',
        'print_status' => null,
        'references' => null,
        'refund_denial_reason' => null,
        'refund_requestor' => null,
        'refund_status' => null,
        'shipment_id' => null,
        'shipper_postage_payment_account_balance' => 'double',
        'special_services' => null,
        'status' => null,
        'transaction_date_time' => 'date-time',
        'transaction_id' => null,
        'transaction_type' => null,
        'value_of_goods' => 'double',
        'weight_in_ounces' => 'int32',
        'zone' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'adjustment_reason' => 'adjustmentReason',
        'credit_card_fee' => 'creditCardFee',
        'custom_message1' => 'customMessage1',
        'custom_message2' => 'customMessage2',
        'description' => 'description',
        'destination_address' => 'destinationAddress',
        'destination_country' => 'destinationCountry',
        'destination_zip' => 'destinationZip',
        'developer_id' => 'developerId',
        'developer_name' => 'developerName',
        'developer_postage_payment_account_balance' => 'developerPostagePaymentAccountBalance',
        'developer_postage_payment_method' => 'developerPostagePaymentMethod',
        'developer_rate_amount' => 'developerRateAmount',
        'developer_rate_plan' => 'developerRatePlan',
        'dimensional_weight_oz' => 'dimensionalWeightOz',
        'external_id' => 'externalId',
        'international_country_price_group' => 'internationalCountryPriceGroup',
        'label_fee' => 'labelFee',
        'mail_class' => 'mailClass',
        'merchant_id' => 'merchantId',
        'merchant_name' => 'merchantName',
        'merchant_postage_account_payment_method' => 'merchantPostageAccountPaymentMethod',
        'merchant_rate' => 'merchantRate',
        'merchant_rate_plan' => 'merchantRatePlan',
        'meter_number' => 'meterNumber',
        'origin_zip' => 'originZip',
        'origination_address' => 'originationAddress',
        'package_height_in_inches' => 'packageHeightInInches',
        'package_length_in_inches' => 'packageLengthInInches',
        'package_type' => 'packageType',
        'package_type_indicator' => 'packageTypeIndicator',
        'package_width_in_inches' => 'packageWidthInInches',
        'parcel_tracking_number' => 'parcelTrackingNumber',
        'postage_deposit_amount' => 'postageDepositAmount',
        'print_status' => 'printStatus',
        'references' => 'references',
        'refund_denial_reason' => 'refundDenialReason',
        'refund_requestor' => 'refundRequestor',
        'refund_status' => 'refundStatus',
        'shipment_id' => 'shipmentId',
        'shipper_postage_payment_account_balance' => 'shipperPostagePaymentAccountBalance',
        'special_services' => 'specialServices',
        'status' => 'status',
        'transaction_date_time' => 'transactionDateTime',
        'transaction_id' => 'transactionId',
        'transaction_type' => 'transactionType',
        'value_of_goods' => 'valueOfGoods',
        'weight_in_ounces' => 'weightInOunces',
        'zone' => 'zone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'adjustment_reason' => 'setAdjustmentReason',
        'credit_card_fee' => 'setCreditCardFee',
        'custom_message1' => 'setCustomMessage1',
        'custom_message2' => 'setCustomMessage2',
        'description' => 'setDescription',
        'destination_address' => 'setDestinationAddress',
        'destination_country' => 'setDestinationCountry',
        'destination_zip' => 'setDestinationZip',
        'developer_id' => 'setDeveloperId',
        'developer_name' => 'setDeveloperName',
        'developer_postage_payment_account_balance' => 'setDeveloperPostagePaymentAccountBalance',
        'developer_postage_payment_method' => 'setDeveloperPostagePaymentMethod',
        'developer_rate_amount' => 'setDeveloperRateAmount',
        'developer_rate_plan' => 'setDeveloperRatePlan',
        'dimensional_weight_oz' => 'setDimensionalWeightOz',
        'external_id' => 'setExternalId',
        'international_country_price_group' => 'setInternationalCountryPriceGroup',
        'label_fee' => 'setLabelFee',
        'mail_class' => 'setMailClass',
        'merchant_id' => 'setMerchantId',
        'merchant_name' => 'setMerchantName',
        'merchant_postage_account_payment_method' => 'setMerchantPostageAccountPaymentMethod',
        'merchant_rate' => 'setMerchantRate',
        'merchant_rate_plan' => 'setMerchantRatePlan',
        'meter_number' => 'setMeterNumber',
        'origin_zip' => 'setOriginZip',
        'origination_address' => 'setOriginationAddress',
        'package_height_in_inches' => 'setPackageHeightInInches',
        'package_length_in_inches' => 'setPackageLengthInInches',
        'package_type' => 'setPackageType',
        'package_type_indicator' => 'setPackageTypeIndicator',
        'package_width_in_inches' => 'setPackageWidthInInches',
        'parcel_tracking_number' => 'setParcelTrackingNumber',
        'postage_deposit_amount' => 'setPostageDepositAmount',
        'print_status' => 'setPrintStatus',
        'references' => 'setReferences',
        'refund_denial_reason' => 'setRefundDenialReason',
        'refund_requestor' => 'setRefundRequestor',
        'refund_status' => 'setRefundStatus',
        'shipment_id' => 'setShipmentId',
        'shipper_postage_payment_account_balance' => 'setShipperPostagePaymentAccountBalance',
        'special_services' => 'setSpecialServices',
        'status' => 'setStatus',
        'transaction_date_time' => 'setTransactionDateTime',
        'transaction_id' => 'setTransactionId',
        'transaction_type' => 'setTransactionType',
        'value_of_goods' => 'setValueOfGoods',
        'weight_in_ounces' => 'setWeightInOunces',
        'zone' => 'setZone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'adjustment_reason' => 'getAdjustmentReason',
        'credit_card_fee' => 'getCreditCardFee',
        'custom_message1' => 'getCustomMessage1',
        'custom_message2' => 'getCustomMessage2',
        'description' => 'getDescription',
        'destination_address' => 'getDestinationAddress',
        'destination_country' => 'getDestinationCountry',
        'destination_zip' => 'getDestinationZip',
        'developer_id' => 'getDeveloperId',
        'developer_name' => 'getDeveloperName',
        'developer_postage_payment_account_balance' => 'getDeveloperPostagePaymentAccountBalance',
        'developer_postage_payment_method' => 'getDeveloperPostagePaymentMethod',
        'developer_rate_amount' => 'getDeveloperRateAmount',
        'developer_rate_plan' => 'getDeveloperRatePlan',
        'dimensional_weight_oz' => 'getDimensionalWeightOz',
        'external_id' => 'getExternalId',
        'international_country_price_group' => 'getInternationalCountryPriceGroup',
        'label_fee' => 'getLabelFee',
        'mail_class' => 'getMailClass',
        'merchant_id' => 'getMerchantId',
        'merchant_name' => 'getMerchantName',
        'merchant_postage_account_payment_method' => 'getMerchantPostageAccountPaymentMethod',
        'merchant_rate' => 'getMerchantRate',
        'merchant_rate_plan' => 'getMerchantRatePlan',
        'meter_number' => 'getMeterNumber',
        'origin_zip' => 'getOriginZip',
        'origination_address' => 'getOriginationAddress',
        'package_height_in_inches' => 'getPackageHeightInInches',
        'package_length_in_inches' => 'getPackageLengthInInches',
        'package_type' => 'getPackageType',
        'package_type_indicator' => 'getPackageTypeIndicator',
        'package_width_in_inches' => 'getPackageWidthInInches',
        'parcel_tracking_number' => 'getParcelTrackingNumber',
        'postage_deposit_amount' => 'getPostageDepositAmount',
        'print_status' => 'getPrintStatus',
        'references' => 'getReferences',
        'refund_denial_reason' => 'getRefundDenialReason',
        'refund_requestor' => 'getRefundRequestor',
        'refund_status' => 'getRefundStatus',
        'shipment_id' => 'getShipmentId',
        'shipper_postage_payment_account_balance' => 'getShipperPostagePaymentAccountBalance',
        'special_services' => 'getSpecialServices',
        'status' => 'getStatus',
        'transaction_date_time' => 'getTransactionDateTime',
        'transaction_id' => 'getTransactionId',
        'transaction_type' => 'getTransactionType',
        'value_of_goods' => 'getValueOfGoods',
        'weight_in_ounces' => 'getWeightInOunces',
        'zone' => 'getZone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['adjustment_reason'] = isset($data['adjustment_reason']) ? $data['adjustment_reason'] : null;
        $this->container['credit_card_fee'] = isset($data['credit_card_fee']) ? $data['credit_card_fee'] : null;
        $this->container['custom_message1'] = isset($data['custom_message1']) ? $data['custom_message1'] : null;
        $this->container['custom_message2'] = isset($data['custom_message2']) ? $data['custom_message2'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['destination_address'] = isset($data['destination_address']) ? $data['destination_address'] : null;
        $this->container['destination_country'] = isset($data['destination_country']) ? $data['destination_country'] : null;
        $this->container['destination_zip'] = isset($data['destination_zip']) ? $data['destination_zip'] : null;
        $this->container['developer_id'] = isset($data['developer_id']) ? $data['developer_id'] : null;
        $this->container['developer_name'] = isset($data['developer_name']) ? $data['developer_name'] : null;
        $this->container['developer_postage_payment_account_balance'] = isset($data['developer_postage_payment_account_balance']) ? $data['developer_postage_payment_account_balance'] : null;
        $this->container['developer_postage_payment_method'] = isset($data['developer_postage_payment_method']) ? $data['developer_postage_payment_method'] : null;
        $this->container['developer_rate_amount'] = isset($data['developer_rate_amount']) ? $data['developer_rate_amount'] : null;
        $this->container['developer_rate_plan'] = isset($data['developer_rate_plan']) ? $data['developer_rate_plan'] : null;
        $this->container['dimensional_weight_oz'] = isset($data['dimensional_weight_oz']) ? $data['dimensional_weight_oz'] : null;
        $this->container['external_id'] = isset($data['external_id']) ? $data['external_id'] : null;
        $this->container['international_country_price_group'] = isset($data['international_country_price_group']) ? $data['international_country_price_group'] : null;
        $this->container['label_fee'] = isset($data['label_fee']) ? $data['label_fee'] : null;
        $this->container['mail_class'] = isset($data['mail_class']) ? $data['mail_class'] : null;
        $this->container['merchant_id'] = isset($data['merchant_id']) ? $data['merchant_id'] : null;
        $this->container['merchant_name'] = isset($data['merchant_name']) ? $data['merchant_name'] : null;
        $this->container['merchant_postage_account_payment_method'] = isset($data['merchant_postage_account_payment_method']) ? $data['merchant_postage_account_payment_method'] : null;
        $this->container['merchant_rate'] = isset($data['merchant_rate']) ? $data['merchant_rate'] : null;
        $this->container['merchant_rate_plan'] = isset($data['merchant_rate_plan']) ? $data['merchant_rate_plan'] : null;
        $this->container['meter_number'] = isset($data['meter_number']) ? $data['meter_number'] : null;
        $this->container['origin_zip'] = isset($data['origin_zip']) ? $data['origin_zip'] : null;
        $this->container['origination_address'] = isset($data['origination_address']) ? $data['origination_address'] : null;
        $this->container['package_height_in_inches'] = isset($data['package_height_in_inches']) ? $data['package_height_in_inches'] : null;
        $this->container['package_length_in_inches'] = isset($data['package_length_in_inches']) ? $data['package_length_in_inches'] : null;
        $this->container['package_type'] = isset($data['package_type']) ? $data['package_type'] : null;
        $this->container['package_type_indicator'] = isset($data['package_type_indicator']) ? $data['package_type_indicator'] : null;
        $this->container['package_width_in_inches'] = isset($data['package_width_in_inches']) ? $data['package_width_in_inches'] : null;
        $this->container['parcel_tracking_number'] = isset($data['parcel_tracking_number']) ? $data['parcel_tracking_number'] : null;
        $this->container['postage_deposit_amount'] = isset($data['postage_deposit_amount']) ? $data['postage_deposit_amount'] : null;
        $this->container['print_status'] = isset($data['print_status']) ? $data['print_status'] : null;
        $this->container['references'] = isset($data['references']) ? $data['references'] : null;
        $this->container['refund_denial_reason'] = isset($data['refund_denial_reason']) ? $data['refund_denial_reason'] : null;
        $this->container['refund_requestor'] = isset($data['refund_requestor']) ? $data['refund_requestor'] : null;
        $this->container['refund_status'] = isset($data['refund_status']) ? $data['refund_status'] : null;
        $this->container['shipment_id'] = isset($data['shipment_id']) ? $data['shipment_id'] : null;
        $this->container['shipper_postage_payment_account_balance'] = isset($data['shipper_postage_payment_account_balance']) ? $data['shipper_postage_payment_account_balance'] : null;
        $this->container['special_services'] = isset($data['special_services']) ? $data['special_services'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['transaction_date_time'] = isset($data['transaction_date_time']) ? $data['transaction_date_time'] : null;
        $this->container['transaction_id'] = isset($data['transaction_id']) ? $data['transaction_id'] : null;
        $this->container['transaction_type'] = isset($data['transaction_type']) ? $data['transaction_type'] : null;
        $this->container['value_of_goods'] = isset($data['value_of_goods']) ? $data['value_of_goods'] : null;
        $this->container['weight_in_ounces'] = isset($data['weight_in_ounces']) ? $data['weight_in_ounces'] : null;
        $this->container['zone'] = isset($data['zone']) ? $data['zone'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets adjustment_reason
     *
     * @return string|null
     */
    public function getAdjustmentReason()
    {
        return $this->container['adjustment_reason'];
    }

    /**
     * Sets adjustment_reason
     *
     * @param string|null $adjustment_reason adjustment_reason
     *
     * @return $this
     */
    public function setAdjustmentReason($adjustment_reason)
    {
        $this->container['adjustment_reason'] = $adjustment_reason;

        return $this;
    }

    /**
     * Gets credit_card_fee
     *
     * @return double|null
     */
    public function getCreditCardFee()
    {
        return $this->container['credit_card_fee'];
    }

    /**
     * Sets credit_card_fee
     *
     * @param double|null $credit_card_fee credit_card_fee
     *
     * @return $this
     */
    public function setCreditCardFee($credit_card_fee)
    {
        $this->container['credit_card_fee'] = $credit_card_fee;

        return $this;
    }

    /**
     * Gets custom_message1
     *
     * @return string|null
     */
    public function getCustomMessage1()
    {
        return $this->container['custom_message1'];
    }

    /**
     * Sets custom_message1
     *
     * @param string|null $custom_message1 custom_message1
     *
     * @return $this
     */
    public function setCustomMessage1($custom_message1)
    {
        $this->container['custom_message1'] = $custom_message1;

        return $this;
    }

    /**
     * Gets custom_message2
     *
     * @return string|null
     */
    public function getCustomMessage2()
    {
        return $this->container['custom_message2'];
    }

    /**
     * Sets custom_message2
     *
     * @param string|null $custom_message2 custom_message2
     *
     * @return $this
     */
    public function setCustomMessage2($custom_message2)
    {
        $this->container['custom_message2'] = $custom_message2;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets destination_address
     *
     * @return string|null
     */
    public function getDestinationAddress()
    {
        return $this->container['destination_address'];
    }

    /**
     * Sets destination_address
     *
     * @param string|null $destination_address destination_address
     *
     * @return $this
     */
    public function setDestinationAddress($destination_address)
    {
        $this->container['destination_address'] = $destination_address;

        return $this;
    }

    /**
     * Gets destination_country
     *
     * @return string|null
     */
    public function getDestinationCountry()
    {
        return $this->container['destination_country'];
    }

    /**
     * Sets destination_country
     *
     * @param string|null $destination_country destination_country
     *
     * @return $this
     */
    public function setDestinationCountry($destination_country)
    {
        $this->container['destination_country'] = $destination_country;

        return $this;
    }

    /**
     * Gets destination_zip
     *
     * @return string|null
     */
    public function getDestinationZip()
    {
        return $this->container['destination_zip'];
    }

    /**
     * Sets destination_zip
     *
     * @param string|null $destination_zip destination_zip
     *
     * @return $this
     */
    public function setDestinationZip($destination_zip)
    {
        $this->container['destination_zip'] = $destination_zip;

        return $this;
    }

    /**
     * Gets developer_id
     *
     * @return string|null
     */
    public function getDeveloperId()
    {
        return $this->container['developer_id'];
    }

    /**
     * Sets developer_id
     *
     * @param string|null $developer_id developer_id
     *
     * @return $this
     */
    public function setDeveloperId($developer_id)
    {
        $this->container['developer_id'] = $developer_id;

        return $this;
    }

    /**
     * Gets developer_name
     *
     * @return string|null
     */
    public function getDeveloperName()
    {
        return $this->container['developer_name'];
    }

    /**
     * Sets developer_name
     *
     * @param string|null $developer_name developer_name
     *
     * @return $this
     */
    public function setDeveloperName($developer_name)
    {
        $this->container['developer_name'] = $developer_name;

        return $this;
    }

    /**
     * Gets developer_postage_payment_account_balance
     *
     * @return double|null
     */
    public function getDeveloperPostagePaymentAccountBalance()
    {
        return $this->container['developer_postage_payment_account_balance'];
    }

    /**
     * Sets developer_postage_payment_account_balance
     *
     * @param double|null $developer_postage_payment_account_balance developer_postage_payment_account_balance
     *
     * @return $this
     */
    public function setDeveloperPostagePaymentAccountBalance($developer_postage_payment_account_balance)
    {
        $this->container['developer_postage_payment_account_balance'] = $developer_postage_payment_account_balance;

        return $this;
    }

    /**
     * Gets developer_postage_payment_method
     *
     * @return string|null
     */
    public function getDeveloperPostagePaymentMethod()
    {
        return $this->container['developer_postage_payment_method'];
    }

    /**
     * Sets developer_postage_payment_method
     *
     * @param string|null $developer_postage_payment_method developer_postage_payment_method
     *
     * @return $this
     */
    public function setDeveloperPostagePaymentMethod($developer_postage_payment_method)
    {
        $this->container['developer_postage_payment_method'] = $developer_postage_payment_method;

        return $this;
    }

    /**
     * Gets developer_rate_amount
     *
     * @return double|null
     */
    public function getDeveloperRateAmount()
    {
        return $this->container['developer_rate_amount'];
    }

    /**
     * Sets developer_rate_amount
     *
     * @param double|null $developer_rate_amount developer_rate_amount
     *
     * @return $this
     */
    public function setDeveloperRateAmount($developer_rate_amount)
    {
        $this->container['developer_rate_amount'] = $developer_rate_amount;

        return $this;
    }

    /**
     * Gets developer_rate_plan
     *
     * @return string|null
     */
    public function getDeveloperRatePlan()
    {
        return $this->container['developer_rate_plan'];
    }

    /**
     * Sets developer_rate_plan
     *
     * @param string|null $developer_rate_plan developer_rate_plan
     *
     * @return $this
     */
    public function setDeveloperRatePlan($developer_rate_plan)
    {
        $this->container['developer_rate_plan'] = $developer_rate_plan;

        return $this;
    }

    /**
     * Gets dimensional_weight_oz
     *
     * @return double|null
     */
    public function getDimensionalWeightOz()
    {
        return $this->container['dimensional_weight_oz'];
    }

    /**
     * Sets dimensional_weight_oz
     *
     * @param double|null $dimensional_weight_oz dimensional_weight_oz
     *
     * @return $this
     */
    public function setDimensionalWeightOz($dimensional_weight_oz)
    {
        $this->container['dimensional_weight_oz'] = $dimensional_weight_oz;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return $this
     */
    public function setExternalId($external_id)
    {
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets international_country_price_group
     *
     * @return string|null
     */
    public function getInternationalCountryPriceGroup()
    {
        return $this->container['international_country_price_group'];
    }

    /**
     * Sets international_country_price_group
     *
     * @param string|null $international_country_price_group international_country_price_group
     *
     * @return $this
     */
    public function setInternationalCountryPriceGroup($international_country_price_group)
    {
        $this->container['international_country_price_group'] = $international_country_price_group;

        return $this;
    }

    /**
     * Gets label_fee
     *
     * @return string|null
     */
    public function getLabelFee()
    {
        return $this->container['label_fee'];
    }

    /**
     * Sets label_fee
     *
     * @param string|null $label_fee label_fee
     *
     * @return $this
     */
    public function setLabelFee($label_fee)
    {
        $this->container['label_fee'] = $label_fee;

        return $this;
    }

    /**
     * Gets mail_class
     *
     * @return string|null
     */
    public function getMailClass()
    {
        return $this->container['mail_class'];
    }

    /**
     * Sets mail_class
     *
     * @param string|null $mail_class mail_class
     *
     * @return $this
     */
    public function setMailClass($mail_class)
    {
        $this->container['mail_class'] = $mail_class;

        return $this;
    }

    /**
     * Gets merchant_id
     *
     * @return string|null
     */
    public function getMerchantId()
    {
        return $this->container['merchant_id'];
    }

    /**
     * Sets merchant_id
     *
     * @param string|null $merchant_id merchant_id
     *
     * @return $this
     */
    public function setMerchantId($merchant_id)
    {
        $this->container['merchant_id'] = $merchant_id;

        return $this;
    }

    /**
     * Gets merchant_name
     *
     * @return string|null
     */
    public function getMerchantName()
    {
        return $this->container['merchant_name'];
    }

    /**
     * Sets merchant_name
     *
     * @param string|null $merchant_name merchant_name
     *
     * @return $this
     */
    public function setMerchantName($merchant_name)
    {
        $this->container['merchant_name'] = $merchant_name;

        return $this;
    }

    /**
     * Gets merchant_postage_account_payment_method
     *
     * @return string|null
     */
    public function getMerchantPostageAccountPaymentMethod()
    {
        return $this->container['merchant_postage_account_payment_method'];
    }

    /**
     * Sets merchant_postage_account_payment_method
     *
     * @param string|null $merchant_postage_account_payment_method merchant_postage_account_payment_method
     *
     * @return $this
     */
    public function setMerchantPostageAccountPaymentMethod($merchant_postage_account_payment_method)
    {
        $this->container['merchant_postage_account_payment_method'] = $merchant_postage_account_payment_method;

        return $this;
    }

    /**
     * Gets merchant_rate
     *
     * @return double|null
     */
    public function getMerchantRate()
    {
        return $this->container['merchant_rate'];
    }

    /**
     * Sets merchant_rate
     *
     * @param double|null $merchant_rate merchant_rate
     *
     * @return $this
     */
    public function setMerchantRate($merchant_rate)
    {
        $this->container['merchant_rate'] = $merchant_rate;

        return $this;
    }

    /**
     * Gets merchant_rate_plan
     *
     * @return string|null
     */
    public function getMerchantRatePlan()
    {
        return $this->container['merchant_rate_plan'];
    }

    /**
     * Sets merchant_rate_plan
     *
     * @param string|null $merchant_rate_plan merchant_rate_plan
     *
     * @return $this
     */
    public function setMerchantRatePlan($merchant_rate_plan)
    {
        $this->container['merchant_rate_plan'] = $merchant_rate_plan;

        return $this;
    }

    /**
     * Gets meter_number
     *
     * @return string|null
     */
    public function getMeterNumber()
    {
        return $this->container['meter_number'];
    }

    /**
     * Sets meter_number
     *
     * @param string|null $meter_number meter_number
     *
     * @return $this
     */
    public function setMeterNumber($meter_number)
    {
        $this->container['meter_number'] = $meter_number;

        return $this;
    }

    /**
     * Gets origin_zip
     *
     * @return string|null
     */
    public function getOriginZip()
    {
        return $this->container['origin_zip'];
    }

    /**
     * Sets origin_zip
     *
     * @param string|null $origin_zip origin_zip
     *
     * @return $this
     */
    public function setOriginZip($origin_zip)
    {
        $this->container['origin_zip'] = $origin_zip;

        return $this;
    }

    /**
     * Gets origination_address
     *
     * @return string|null
     */
    public function getOriginationAddress()
    {
        return $this->container['origination_address'];
    }

    /**
     * Sets origination_address
     *
     * @param string|null $origination_address origination_address
     *
     * @return $this
     */
    public function setOriginationAddress($origination_address)
    {
        $this->container['origination_address'] = $origination_address;

        return $this;
    }

    /**
     * Gets package_height_in_inches
     *
     * @return double|null
     */
    public function getPackageHeightInInches()
    {
        return $this->container['package_height_in_inches'];
    }

    /**
     * Sets package_height_in_inches
     *
     * @param double|null $package_height_in_inches package_height_in_inches
     *
     * @return $this
     */
    public function setPackageHeightInInches($package_height_in_inches)
    {
        $this->container['package_height_in_inches'] = $package_height_in_inches;

        return $this;
    }

    /**
     * Gets package_length_in_inches
     *
     * @return double|null
     */
    public function getPackageLengthInInches()
    {
        return $this->container['package_length_in_inches'];
    }

    /**
     * Sets package_length_in_inches
     *
     * @param double|null $package_length_in_inches package_length_in_inches
     *
     * @return $this
     */
    public function setPackageLengthInInches($package_length_in_inches)
    {
        $this->container['package_length_in_inches'] = $package_length_in_inches;

        return $this;
    }

    /**
     * Gets package_type
     *
     * @return string|null
     */
    public function getPackageType()
    {
        return $this->container['package_type'];
    }

    /**
     * Sets package_type
     *
     * @param string|null $package_type package_type
     *
     * @return $this
     */
    public function setPackageType($package_type)
    {
        $this->container['package_type'] = $package_type;

        return $this;
    }

    /**
     * Gets package_type_indicator
     *
     * @return string|null
     */
    public function getPackageTypeIndicator()
    {
        return $this->container['package_type_indicator'];
    }

    /**
     * Sets package_type_indicator
     *
     * @param string|null $package_type_indicator package_type_indicator
     *
     * @return $this
     */
    public function setPackageTypeIndicator($package_type_indicator)
    {
        $this->container['package_type_indicator'] = $package_type_indicator;

        return $this;
    }

    /**
     * Gets package_width_in_inches
     *
     * @return double|null
     */
    public function getPackageWidthInInches()
    {
        return $this->container['package_width_in_inches'];
    }

    /**
     * Sets package_width_in_inches
     *
     * @param double|null $package_width_in_inches package_width_in_inches
     *
     * @return $this
     */
    public function setPackageWidthInInches($package_width_in_inches)
    {
        $this->container['package_width_in_inches'] = $package_width_in_inches;

        return $this;
    }

    /**
     * Gets parcel_tracking_number
     *
     * @return string|null
     */
    public function getParcelTrackingNumber()
    {
        return $this->container['parcel_tracking_number'];
    }

    /**
     * Sets parcel_tracking_number
     *
     * @param string|null $parcel_tracking_number parcel_tracking_number
     *
     * @return $this
     */
    public function setParcelTrackingNumber($parcel_tracking_number)
    {
        $this->container['parcel_tracking_number'] = $parcel_tracking_number;

        return $this;
    }

    /**
     * Gets postage_deposit_amount
     *
     * @return double|null
     */
    public function getPostageDepositAmount()
    {
        return $this->container['postage_deposit_amount'];
    }

    /**
     * Sets postage_deposit_amount
     *
     * @param double|null $postage_deposit_amount postage_deposit_amount
     *
     * @return $this
     */
    public function setPostageDepositAmount($postage_deposit_amount)
    {
        $this->container['postage_deposit_amount'] = $postage_deposit_amount;

        return $this;
    }

    /**
     * Gets print_status
     *
     * @return string|null
     */
    public function getPrintStatus()
    {
        return $this->container['print_status'];
    }

    /**
     * Sets print_status
     *
     * @param string|null $print_status print_status
     *
     * @return $this
     */
    public function setPrintStatus($print_status)
    {
        $this->container['print_status'] = $print_status;

        return $this;
    }

    /**
     * Gets references
     *
     * @return \pitneybowesShipping\shippingApi.model\Parameter[]|null
     */
    public function getReferences()
    {
        return $this->container['references'];
    }

    /**
     * Sets references
     *
     * @param \pitneybowesShipping\shippingApi.model\Parameter[]|null $references references
     *
     * @return $this
     */
    public function setReferences($references)
    {
        $this->container['references'] = $references;

        return $this;
    }

    /**
     * Gets refund_denial_reason
     *
     * @return string|null
     */
    public function getRefundDenialReason()
    {
        return $this->container['refund_denial_reason'];
    }

    /**
     * Sets refund_denial_reason
     *
     * @param string|null $refund_denial_reason refund_denial_reason
     *
     * @return $this
     */
    public function setRefundDenialReason($refund_denial_reason)
    {
        $this->container['refund_denial_reason'] = $refund_denial_reason;

        return $this;
    }

    /**
     * Gets refund_requestor
     *
     * @return string|null
     */
    public function getRefundRequestor()
    {
        return $this->container['refund_requestor'];
    }

    /**
     * Sets refund_requestor
     *
     * @param string|null $refund_requestor refund_requestor
     *
     * @return $this
     */
    public function setRefundRequestor($refund_requestor)
    {
        $this->container['refund_requestor'] = $refund_requestor;

        return $this;
    }

    /**
     * Gets refund_status
     *
     * @return string|null
     */
    public function getRefundStatus()
    {
        return $this->container['refund_status'];
    }

    /**
     * Sets refund_status
     *
     * @param string|null $refund_status refund_status
     *
     * @return $this
     */
    public function setRefundStatus($refund_status)
    {
        $this->container['refund_status'] = $refund_status;

        return $this;
    }

    /**
     * Gets shipment_id
     *
     * @return string|null
     */
    public function getShipmentId()
    {
        return $this->container['shipment_id'];
    }

    /**
     * Sets shipment_id
     *
     * @param string|null $shipment_id shipment_id
     *
     * @return $this
     */
    public function setShipmentId($shipment_id)
    {
        $this->container['shipment_id'] = $shipment_id;

        return $this;
    }

    /**
     * Gets shipper_postage_payment_account_balance
     *
     * @return double|null
     */
    public function getShipperPostagePaymentAccountBalance()
    {
        return $this->container['shipper_postage_payment_account_balance'];
    }

    /**
     * Sets shipper_postage_payment_account_balance
     *
     * @param double|null $shipper_postage_payment_account_balance shipper_postage_payment_account_balance
     *
     * @return $this
     */
    public function setShipperPostagePaymentAccountBalance($shipper_postage_payment_account_balance)
    {
        $this->container['shipper_postage_payment_account_balance'] = $shipper_postage_payment_account_balance;

        return $this;
    }

    /**
     * Gets special_services
     *
     * @return \pitneybowesShipping\shippingApi.model\SpecialService[]|null
     */
    public function getSpecialServices()
    {
        return $this->container['special_services'];
    }

    /**
     * Sets special_services
     *
     * @param \pitneybowesShipping\shippingApi.model\SpecialService[]|null $special_services special_services
     *
     * @return $this
     */
    public function setSpecialServices($special_services)
    {
        $this->container['special_services'] = $special_services;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets transaction_date_time
     *
     * @return \DateTime|null
     */
    public function getTransactionDateTime()
    {
        return $this->container['transaction_date_time'];
    }

    /**
     * Sets transaction_date_time
     *
     * @param \DateTime|null $transaction_date_time transaction_date_time
     *
     * @return $this
     */
    public function setTransactionDateTime($transaction_date_time)
    {
        $this->container['transaction_date_time'] = $transaction_date_time;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return string|null
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string|null $transaction_id transaction_id
     *
     * @return $this
     */
    public function setTransactionId($transaction_id)
    {
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets transaction_type
     *
     * @return string|null
     */
    public function getTransactionType()
    {
        return $this->container['transaction_type'];
    }

    /**
     * Sets transaction_type
     *
     * @param string|null $transaction_type transaction_type
     *
     * @return $this
     */
    public function setTransactionType($transaction_type)
    {
        $this->container['transaction_type'] = $transaction_type;

        return $this;
    }

    /**
     * Gets value_of_goods
     *
     * @return double|null
     */
    public function getValueOfGoods()
    {
        return $this->container['value_of_goods'];
    }

    /**
     * Sets value_of_goods
     *
     * @param double|null $value_of_goods value_of_goods
     *
     * @return $this
     */
    public function setValueOfGoods($value_of_goods)
    {
        $this->container['value_of_goods'] = $value_of_goods;

        return $this;
    }

    /**
     * Gets weight_in_ounces
     *
     * @return int|null
     */
    public function getWeightInOunces()
    {
        return $this->container['weight_in_ounces'];
    }

    /**
     * Sets weight_in_ounces
     *
     * @param int|null $weight_in_ounces weight_in_ounces
     *
     * @return $this
     */
    public function setWeightInOunces($weight_in_ounces)
    {
        $this->container['weight_in_ounces'] = $weight_in_ounces;

        return $this;
    }

    /**
     * Gets zone
     *
     * @return string|null
     */
    public function getZone()
    {
        return $this->container['zone'];
    }

    /**
     * Sets zone
     *
     * @param string|null $zone zone
     *
     * @return $this
     */
    public function setZone($zone)
    {
        $this->container['zone'] = $zone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


