<?php
/**
 * BatteryDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pitneybowesShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace pitneybowesShipping;

use PHPUnit\Framework\TestCase;

/**
 * BatteryDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description BatteryDetails
 * @package     pitneybowesShipping
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BatteryDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BatteryDetails"
     */
    public function testBatteryDetails()
    {
    }

    /**
     * Test attribute "battery_material"
     */
    public function testPropertyBatteryMaterial()
    {
    }

    /**
     * Test attribute "battery_packaging"
     */
    public function testPropertyBatteryPackaging()
    {
    }

    /**
     * Test attribute "regulatory"
     */
    public function testPropertyRegulatory()
    {
    }
}
