<?php
/**
 * CrossBorderQuotesRequestPricingCodPriceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pitneybowesShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace pitneybowesShipping;

use PHPUnit\Framework\TestCase;

/**
 * CrossBorderQuotesRequestPricingCodPriceTest Class Doc Comment
 *
 * @category    Class
 * @description CrossBorderQuotesRequestPricingCodPrice
 * @package     pitneybowesShipping
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CrossBorderQuotesRequestPricingCodPriceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CrossBorderQuotesRequestPricingCodPrice"
     */
    public function testCrossBorderQuotesRequestPricingCodPrice()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "cod"
     */
    public function testPropertyCod()
    {
    }

    /**
     * Test attribute "includes_duty"
     */
    public function testPropertyIncludesDuty()
    {
    }

    /**
     * Test attribute "includes_taxes"
     */
    public function testPropertyIncludesTaxes()
    {
    }
}
