<?php
/**
 * ManifestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ManifestTest Class Doc Comment
 *
 * @category    Class
 * @description Manifest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ManifestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Manifest"
     */
    public function testManifest()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "from_address"
     */
    public function testPropertyFromAddress()
    {
    }

    /**
     * Test attribute "induction_postal_code"
     */
    public function testPropertyInductionPostalCode()
    {
    }

    /**
     * Test attribute "manifest_id"
     */
    public function testPropertyManifestId()
    {
    }

    /**
     * Test attribute "manifest_tracking_number"
     */
    public function testPropertyManifestTrackingNumber()
    {
    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {
    }

    /**
     * Test attribute "parcel_tracking_numbers"
     */
    public function testPropertyParcelTrackingNumbers()
    {
    }

    /**
     * Test attribute "submission_date"
     */
    public function testPropertySubmissionDate()
    {
    }
}
