<?php
/**
 * ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pitneybowesShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace pitneybowesShipping;

use PHPUnit\Framework\TestCase;

/**
 * ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddressTest Class Doc Comment
 *
 * @category    Class
 * @description ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress
 * @package     pitneybowesShipping
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress"
     */
    public function testParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress()
    {
    }

    /**
     * Test attribute "address_lines"
     */
    public function testPropertyAddressLines()
    {
    }

    /**
     * Test attribute "city_town"
     */
    public function testPropertyCityTown()
    {
    }

    /**
     * Test attribute "state_province"
     */
    public function testPropertyStateProvince()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }
}
