<?php
/**
 * ParcelProtectionPolicyResponseSortTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ParcelProtectionPolicyResponseSortTest Class Doc Comment
 *
 * @category    Class
 * @description ParcelProtectionPolicyResponseSort
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParcelProtectionPolicyResponseSortTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ParcelProtectionPolicyResponseSort"
     */
    public function testParcelProtectionPolicyResponseSort()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "property"
     */
    public function testPropertyProperty()
    {
    }

    /**
     * Test attribute "ignore_case"
     */
    public function testPropertyIgnoreCase()
    {
    }

    /**
     * Test attribute "null_handling"
     */
    public function testPropertyNullHandling()
    {
    }

    /**
     * Test attribute "descending"
     */
    public function testPropertyDescending()
    {
    }

    /**
     * Test attribute "ascending"
     */
    public function testPropertyAscending()
    {
    }
}
