<?php
/**
 * ParcelProtectionPolicyResponseShipmentDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ParcelProtectionPolicyResponseShipmentDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description ParcelProtectionPolicyResponseShipmentDetails
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParcelProtectionPolicyResponseShipmentDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ParcelProtectionPolicyResponseShipmentDetails"
     */
    public function testParcelProtectionPolicyResponseShipmentDetails()
    {
    }

    /**
     * Test attribute "shipment_date"
     */
    public function testPropertyShipmentDate()
    {
    }

    /**
     * Test attribute "shipment_transaction_id"
     */
    public function testPropertyShipmentTransactionId()
    {
    }

    /**
     * Test attribute "shipment_id"
     */
    public function testPropertyShipmentId()
    {
    }

    /**
     * Test attribute "parcel_tracking_number"
     */
    public function testPropertyParcelTrackingNumber()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "package_length"
     */
    public function testPropertyPackageLength()
    {
    }

    /**
     * Test attribute "package_width"
     */
    public function testPropertyPackageWidth()
    {
    }

    /**
     * Test attribute "package_height"
     */
    public function testPropertyPackageHeight()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "zone"
     */
    public function testPropertyZone()
    {
    }
}
