<?php
/**
 * ParcelProtectionPolicyResponseContentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ParcelProtectionPolicyResponseContentTest Class Doc Comment
 *
 * @category    Class
 * @description ParcelProtectionPolicyResponseContent
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParcelProtectionPolicyResponseContentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ParcelProtectionPolicyResponseContent"
     */
    public function testParcelProtectionPolicyResponseContent()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "developer_id"
     */
    public function testPropertyDeveloperId()
    {
    }

    /**
     * Test attribute "subscription_acc_no"
     */
    public function testPropertySubscriptionAccNo()
    {
    }

    /**
     * Test attribute "client_transaction_id"
     */
    public function testPropertyClientTransactionId()
    {
    }

    /**
     * Test attribute "policy_details"
     */
    public function testPropertyPolicyDetails()
    {
    }

    /**
     * Test attribute "shipment_details"
     */
    public function testPropertyShipmentDetails()
    {
    }

    /**
     * Test attribute "shipper_info"
     */
    public function testPropertyShipperInfo()
    {
    }

    /**
     * Test attribute "consignee_info"
     */
    public function testPropertyConsigneeInfo()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
