<?php
/**
 * ShipmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentTest Class Doc Comment
 *
 * @category    Class
 * @description Shipment
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Shipment"
     */
    public function testShipment()
    {
    }

    /**
     * Test attribute "additional_addresses"
     */
    public function testPropertyAdditionalAddresses()
    {
    }

    /**
     * Test attribute "alt_return_address"
     */
    public function testPropertyAltReturnAddress()
    {
    }

    /**
     * Test attribute "carrier_payments"
     */
    public function testPropertyCarrierPayments()
    {
    }

    /**
     * Test attribute "customs"
     */
    public function testPropertyCustoms()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "from_address"
     */
    public function testPropertyFromAddress()
    {
    }

    /**
     * Test attribute "hazmat_details"
     */
    public function testPropertyHazmatDetails()
    {
    }

    /**
     * Test attribute "parcel"
     */
    public function testPropertyParcel()
    {
    }

    /**
     * Test attribute "parcel_tracking_number"
     */
    public function testPropertyParcelTrackingNumber()
    {
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
    }

    /**
     * Test attribute "references"
     */
    public function testPropertyReferences()
    {
    }

    /**
     * Test attribute "shipment_id"
     */
    public function testPropertyShipmentId()
    {
    }

    /**
     * Test attribute "shipment_options"
     */
    public function testPropertyShipmentOptions()
    {
    }

    /**
     * Test attribute "shipment_type"
     */
    public function testPropertyShipmentType()
    {
    }

    /**
     * Test attribute "sold_to_address"
     */
    public function testPropertySoldToAddress()
    {
    }

    /**
     * Test attribute "to_address"
     */
    public function testPropertyToAddress()
    {
    }
}
