<?php
/**
 * SpecialServicesRuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pitneybowesShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace pitneybowesShipping;

use PHPUnit\Framework\TestCase;

/**
 * SpecialServicesRuleTest Class Doc Comment
 *
 * @category    Class
 * @description SpecialServicesRule
 * @package     pitneybowesShipping
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SpecialServicesRuleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SpecialServicesRule"
     */
    public function testSpecialServicesRule()
    {
    }

    /**
     * Test attribute "special_service_id"
     */
    public function testPropertySpecialServiceId()
    {
    }

    /**
     * Test attribute "branded_name"
     */
    public function testPropertyBrandedName()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "category_name"
     */
    public function testPropertyCategoryName()
    {
    }

    /**
     * Test attribute "trackable"
     */
    public function testPropertyTrackable()
    {
    }

    /**
     * Test attribute "input_parameter_rules"
     */
    public function testPropertyInputParameterRules()
    {
    }

    /**
     * Test attribute "prerequisite_rules"
     */
    public function testPropertyPrerequisiteRules()
    {
    }

    /**
     * Test attribute "incompatible_special_services"
     */
    public function testPropertyIncompatibleSpecialServices()
    {
    }
}
